name: Create Actions for V3 CKAN Portals from Wikidata
on: [workflow_dispatch]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install Python dependencies
      run: pip install requests

    - name: Run Python Script
      run: python actions/create-api-files.py  # Replace with your script's name
      working-directory: ./actions  

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Auto-update from script" -a || echo "No changes to commit"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: V3 CKAN portals auto creation
        commit-message: V3 CKAN portals auto creation from Wikidata
        branch: update-data
        delete-branch: true
